# Generated by Django 4.0.4 on 2022-05-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_address_zip_alter_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
